import React, { useEffect, useState } from 'react'
import Head from 'next/head'

const Home = () => {

  const [date, setDate] = useState(new Date())

  useEffect(() => {
    document.addEventListener('mousemove', onMouseMove)
    setInterval(() => {
      setDate(new Date())
    }, 1000)
  }, [])

  const onMouseMove = (event: Event) => {
    const card: Element = document.getElementById('clock')
    var ax = -(window.innerWidth / 2 - event?.pageX) / 20;
    var ay = (window.innerHeight / 2 - event?.pageY) / 10;
    ax = ax / 1.7;
    ay = ay / 1.7;

    card.setAttribute("style", `transform: rotateY(${ax}deg) rotateX(${ay}deg);-webkit-transform: rotateY(${ax}deg) rotateX(${ay}deg);-moz-transform: rotateY(${ax}deg) rotateX(${ax}deg)`);
  };

  const seconds = date.getSeconds();
  const mins = date.getMinutes();
  const hour = date.getHours();

  return (
    <>
      <Head>
        <title>The Clock</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="../favicon.png" />
      </Head>

      <div className='container'>
        <div id='clock' className="card">
          <div className="card-content">
            <div className='center' />
            <span className='niddle-hour' style={{ backgroundColor: 'red', transform: `rotate(${((hour / 12) * 360) + ((mins / 60) * 30) + 90}deg)` }} />
            <span className='niddle-minute' style={{ backgroundColor: 'red', transform: `rotate(${((mins / 60) * 360) + ((seconds / 60) * 6) + 90}deg)` }} />
            <span className='niddle-second' style={{ backgroundColor: 'red', transform: `rotate(${((mins * 360) + (seconds / 60) * 360) + 90}deg)` }} />
          </div>
        </div>
        <div className='contact'>
          <span>Created By:&nbsp;</span>
          <span>Nazir Hussain</span>
          <span>Created By:&nbsp;</span>
          <span>Nazir Hussain</span>
        </div>
      </div>
    </>
  )
}

export default Home;
